# Generated by Django 5.1 on 2026-03-23 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discount", models.IntegerField()),
                ("Image", models.ImageField(blank=True, null=True, upload_to="items/")),
                (
                    "Item_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Name",
                        to="base_app.items",
                    ),
                ),
            ],
        ),
    ]
